# Generated by Django 4.1.1 on 2022-09-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('brend', models.CharField(max_length=50)),
                ('olchov', models.CharField(choices=[('kg', 'kg'), ('qop', 'qop'), ('dona', 'dona')], max_length=20)),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('kelgan_sana', models.DateTimeField(auto_now_add=True)),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.omborxona')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('qarz', models.IntegerField(default=0)),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.omborxona')),
            ],
        ),
    ]
