# Generated by Django 4.1.1 on 2022-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='narx',
            field=models.IntegerField(default=32000),
        ),
    ]
