# Generated by Django 4.1.1 on 2022-10-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0002_delete_statistika'),
        ('asosiyapp', '0003_alter_mahsulot_narx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='ombor',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Mahsulot',
        ),
    ]
