# Generated by Django 4.1.1 on 2022-10-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0002_delete_statistika'),
        ('asosiyapp', '0004_remove_mahsulot_ombor_delete_client_delete_mahsulot'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Omborxona',
        ),
    ]
