# Generated by Django 4.1.1 on 2022-10-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sotuvchi',
            name='vazifa',
        ),
    ]
